version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    resource_class: large
    working_directory: ~/argo-react
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo npm i -g codecov node-gyp
            npm i

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.npm
            - ~/.cache

      - run:
          name: check formatting
          command: npm run prettier:check

      - run:
          name: run build
          command: CI=false npm run build

      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: "s3://dev.argoapp.live"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  build-deploy:
    jobs:
      - build
