version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    working_directory: ~/argo-react
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo npm i -g codecov node-gyp
            npm i
            
      - run:
          name: check formatting
          command: npm run prettier:check

      - run:
          name: run build
          command: npm run build

      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: "s3://dev.argoapp.live"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"


workflows:
  build-deploy:
    jobs:
      - build
