version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  formatting:
    working_directory: ~/argo-react
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            sudo npm i -g codecov node-gyp
            npm i

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.npm
            - ~/.cache

      - run:
          name: Check Formatting & Codecov
          command: npm run prettier:write && npm run prettier:check && codecov

  build:
    resource_class: large
    working_directory: ~/argo-react
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            sudo npm i -g codecov node-gyp
            npm i

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.npm
            - ~/.cache

      - run:
          name: Run Build
          command: CI=false npm run build

  deploy:
    working_directory: ~/argo-react
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: "s3://dev.argoapp.live"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  build-deploy:
    jobs:
      - formatting
      - build:
          requires:
            - formatting # Only run deploy job once the build job has completed
          # filters:
          #   branches:
          #     only: dev
      - deploy:
          requires:
            - build # Only run deploy job once the build job has completed
          # filters:
          #   branches:
          #     only: dev
